kind = "mobile"
previewPath = "/"
title = "Elite eSports"
version = "1.0.0"
id = "artifacts/elite-esports"
router = "expo-domain"

[[integratedSkills]]
name = "expo"
version = "1.0.0"

[[services]]
name = "expo"
paths = [ "/" ]
localPort = 18977

[services.development]
run = "pnpm --filter @workspace/elite-esports run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/elite-esports", "run", "build" ]
run = [ "pnpm", "--filter", "@workspace/elite-esports", "run", "serve" ]

[services.env]
PORT = "18977"
BASE_PATH = "/"
