/**
 * withFCMNotificationConfig
 *
 * Adds the three Firebase Cloud Messaging meta-data entries to
 * AndroidManifest.xml that control how notifications look when the app is
 * in the background or completely killed (i.e. FCM delivers the notification
 * directly to the system tray without any JS running):
 *
 *   1. default_notification_icon  → @drawable/ic_notification
 *      The monochrome icon generated by the expo-notifications plugin from
 *      assets/images/icon.png.  Shows in the status bar & top of the drawer.
 *
 *   2. default_notification_channel_id → elite-esports-default
 *      Routes all FCM-delivered notifications through our custom channel so
 *      the correct vibration, sound, and importance level are applied.
 *
 *   3. default_notification_color → @color/notification_color
 *      Tints the icon and the notification accent with the brand orange
 *      (#FE4C11).  The color resource is injected into res/values/colors.xml.
 *
 * Additionally, this plugin sets the large icon for notifications to the
 * full-color launcher icon (@mipmap/ic_launcher) by injecting a meta-data
 * entry recognised by expo-notifications' Android notification builder.
 */

const { withAndroidManifest, withDangerousMod } = require('@expo/config-plugins');
const fs   = require('fs');
const path = require('path');

// ─── 1. AndroidManifest meta-data ────────────────────────────────────────────
function withFCMManifest(config) {
  return withAndroidManifest(config, (cfg) => {
    const manifest   = cfg.modResults.manifest;
    const application = manifest.application?.[0];
    if (!application) return cfg;

    application['meta-data'] = application['meta-data'] ?? [];

    const entries = [
      {
        name:     'com.google.firebase.messaging.default_notification_icon',
        resource: '@drawable/ic_notification',
      },
      {
        name:  'com.google.firebase.messaging.default_notification_channel_id',
        value: 'elite-esports-default',
      },
      {
        name:     'com.google.firebase.messaging.default_notification_color',
        resource: '@color/notification_color',
      },
    ];

    for (const entry of entries) {
      const existing = application['meta-data'].findIndex(
        (m) => m['$']['android:name'] === entry.name,
      );
      const attrs = { 'android:name': entry.name };
      if (entry.resource) attrs['android:resource'] = entry.resource;
      if (entry.value)    attrs['android:value']    = entry.value;

      if (existing >= 0) {
        application['meta-data'][existing]['$'] = attrs;
      } else {
        application['meta-data'].push({ '$': attrs });
      }
    }

    return cfg;
  });
}

// ─── 2. Inject notification_color into res/values/colors.xml ─────────────────
function withNotificationColor(config) {
  return withDangerousMod(config, [
    'android',
    async (cfg) => {
      const projectRoot = cfg.modRequest.projectRoot;
      const valuesDir   = path.join(projectRoot, 'android', 'app', 'src', 'main', 'res', 'values');

      // Only runs during a native build (android dir must exist)
      if (!fs.existsSync(valuesDir)) return cfg;

      const colorsPath = path.join(valuesDir, 'colors.xml');
      let xml;

      if (fs.existsSync(colorsPath)) {
        xml = fs.readFileSync(colorsPath, 'utf8');
        if (xml.includes('notification_color')) return cfg; // already present
        xml = xml.replace('</resources>', '    <color name="notification_color">#FE4C11</color>\n</resources>');
      } else {
        xml = [
          '<?xml version="1.0" encoding="utf-8"?>',
          '<resources>',
          '    <color name="notification_color">#FE4C11</color>',
          '</resources>',
        ].join('\n');
      }

      fs.writeFileSync(colorsPath, xml, 'utf8');
      return cfg;
    },
  ]);
}

// ─── Compose ──────────────────────────────────────────────────────────────────
module.exports = function withFCMNotificationConfig(config) {
  config = withFCMManifest(config);
  config = withNotificationColor(config);
  return config;
};
